---
- name: Query all contracts
  cisco.aci.aci_contract:
    host: "{{ansible_host}}"
    username: "{{ username }}"
    password: "{{ password }}"
    tenant: "SnV"
    state: query
  delegate_to: localhost
  register: query_result

#- name: output of query_result
 # debug:
  #  var: query_result

- name: filtering list of contracts
  ansible.builtin.debug:
    msg: "{{ query_result | community.general.json_query('current[*].fvTenant.children[*].vzBrCP.attributes.name') }}"
      